### ISSUE TITLE
Problems with Wuhan seafood market pneumonia virus

### ISSUE THREAD

**Issue by dsclassen** [lbl-cbg/t5-commons#13]
It seems something is wrong with your new `Wuhan seafood market pneumonia virus`

Logs from React app:

```
Note that the development build is not optimized.
To create a production build, use yarn build.

webpack compiled successfully
Error: ENOENT: no such file or directory, stat '/srv/app/public/species/11036'
```

Error in browser:

```Unexpected Application Error!
Cannot read properties of undefined (reading 'abbr')
TypeError: Cannot read properties of undefined (reading 'abbr')
    at Species (https://t5-brave.als.lbl.gov/static/js/bundle.js:547:76)
    at renderWithHooks (https://t5-brave.als.lbl.gov/static/js/bundle.js:237367:22)
    at mountIndeterminateComponent (https://t5-brave.als.lbl.gov/static/js/bundle.js:240651:17)
    at beginWork (https://t5-brave.als.lbl.gov/static/js/bundle.js:241947:20)
    at beginWork$1 (https://t5-brave.als.lbl.gov/static/js/bundle.js:246906:18)
    at performUnitOfWork (https://t5-brave.als.lbl.gov/static/js/bundle.js:246176:16)
    at workLoopSync (https://t5-brave.als.lbl.gov/static/js/bundle.js:246099:9)
    at renderRootSync (https://t5-brave.als.lbl.gov/static/js/bundle.js:246072:11)
    at recoverFromConcurrentError (https://t5-brave.als.lbl.gov/static/js/bundle.js:245564:24)
    at performSyncWorkOnRoot (https://t5-brave.als.lbl.gov/static/js/bundle.js:245773:24)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

**Comment by yonglbl** [comment]
can you rebuild it? or remove the bundle.js from /static/js, basically on the site the compiled code didn't have the latest changes

**Comment by dsclassen** [comment]
My deploy workflow is as follows:

```bash
git clone git@github.com:lbl-cbg/t5-commons.git
cd t5-commons/BRAVE
docker compose -f docker-compose.prod.yml -p brave build
docker compose -f docker-compose.prod.yml -p brave up -d
```

If there is some bundling step that needs to happen then perhaps we should figure this out.

**Comment by yonglbl** [comment]
not sure what happened, not much different than last deployment. if you rerun the above comments, still have same behavior?

**Comment by yonglbl** [comment]
looks like its updated now

**Comment by dsclassen** [comment]
closing this. not enough info, and not sure it is reproducible.
